default:
  tags:
    - docker

image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  YC_SERVICE_ACCOUNT_KEY_FILE: /tmp/sa-key.json

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - .terraform

before_script:
  - |
    cat <<EOF>> ~/.terraformrc
    provider_installation {
      network_mirror {
        url = "https://terraform-mirror.yandexcloud.net/"
        include = ["registry.terraform.io/*/*"]
      }
      direct {
        exclude = ["registry.terraform.io/*/*"]
      }
    }
    EOF
  - terraform --version
  - terraform init
  - echo $YC_KEY > /tmp/sa-key.json


stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

checkov:
  stage: validate
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  
  script:
    - checkov -d .
  allow_failure: true

# Job: tflint | Stage: Validate
# Purpose: Lint the Terraform configuration using tflint (only works with Terraform 0.12 code)
tflint:
  stage: validate
  image:
    name: wata727/tflint:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint -v
    - tflint
  allow_failure: true


plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  only:
    - main

destroy: 
  stage: destroy
  script:
    - terraform destroy --auto-approve
  when: manual 
  only:
    - main